services:
  # 1. PROXY INVERSO (Nginx)
  proxy:
    image: nginx:alpine
    container_name: laravel-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - euskalspot

  # 2. BACKEND (Laravel)
  backend:
    build:
      context: ./backend
    container_name: laravel-apache
    restart: unless-stopped
    volumes:
      # Código fuente (Persistente en RAID)
      - ./backend/src:/var/www/html
      # REQUISITO SSII: Persistencia de imágenes/multimedia
      # Esto asegura que las fotos subidas se guarden en el RAID
      - ./backend/src/storage/app/public:/var/www/html/storage/app/public
    depends_on:
      - db
    networks:
      - euskalspot

  # 3. FRONTEND (Estático)
  frontend:
    image: nginx:alpine
    container_name: euskalspot-front
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - euskalspot

  # 4. NODE (Desarrollo)
  node:
    image: node:22
    container_name: laravel-node
    working_dir: /var/www/html
    volumes:
      - ./backend/src:/var/www/html
    ports:
      - "5173:5173"
    # Comando ajustado para que no se cierre
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - euskalspot

  # 5. BASE DE DATOS (CRÍTICO PARA SSII)
  db:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 2daw3
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 2daw3
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - euskalspot

  # 6. PHPMYADMIN
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    networks:
      - euskalspot

networks:
  euskalspot:
    driver: bridge
